### ISSUE TITLE
is it outdated?

### ISSUE THREAD

**Issue by blue-eyed-devil** [partnerhero/gapi-script#28]
your live example is throwing :
```
Uncaught TypeError: Cannot read properties of undefined (reading 'init')
    at index.js:13:32
    at gapiScript.js:32:267
    at tb (gapiScript.js:24:468)
    at t (gapiScript.js:32:250)
    at g.<computed> (gapiScript.js:32:353)
    at F.<computed> [as loaded_0] (gapiScript.js:32:417)
    at cb=gapi.loaded_0:1:6
```

**Comment by abenjaminov** [comment]
Also getting this error, following

**Comment by gonzae** [comment]
Getting same error 😢

**Comment by gonzae** [comment]
Looks like this is getting deprecated: https://developers.googleblog.com/2021/08/gsi-jsweb-deprecation.html

This also is related to #29

**Comment by hyperparameters** [comment]
I have Implemented new flow, you can check #29 for steps to reproduce
