### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by jwknz** [partnerhero/gapi-script#4]
Hi I am getting the following error `import { gapi, gapiComplete } from './gapiScript';` with the console output below.

I know this was address is issue #1, but I couldn't find a fix through that.

Any other ideas?

```
[ ready ] compiled successfully - ready on http://localhost:7777
[ error ] /Users/jeff/Projects/ProjectR4L/R4L_Website_App/node_modules/gapi-script/index.js:1
import { gapi, gapiComplete } from './gapiScript';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.gapi-script (/Users/jeff/Projects/ProjectR4L/R4L_Website_App/.next/server/static/development/pages/_app.js:2416:18)
    at __webpack_require__ (/Users/jeff/Projects/ProjectR4L/R4L_Website_App/.next/server/static/development/pages/_app.js:23:31)
    at Module../components/Page.js (/Users/jeff/Projects/ProjectR4L/R4L_Website_App/.next/server/static/development/pages/_app.js:158:69)
    at __webpack_require__ (/Users/jeff/Projects/ProjectR4L/R4L_Website_App/.next/server/static/development/pages/_app.js:23:31)
    at Module../pages/_app.js (/Users/jeff/Projects/ProjectR4L/R4L_Website_App/.next/server/static/development/pages/_app.js:2244:74)
    at __webpack_require__ (/Users/jeff/Projects/ProjectR4L/R4L_Website_App/.next/server/static/development/pages/_app.js:23:31)
    at Object.0 (/Users/jeff/Projects/ProjectR4L/R4L_Website_App/.next/server/static/development/pages/_app.js:2294:18)
    at __webpack_require__ (/Users/jeff/Projects/ProjectR4L/R4L_Website_App/.next/server/static/development/pages/_app.js:23:31)
    at /Users/jeff/Projects/ProjectR4L/R4L_Website_App/.next/server/static/development/pages/_app.js:91:18
/Users/jeff/Projects/ProjectR4L/R4L_Website_App/node_modules/gapi-script/index.js:1
import { gapi, gapiComplete } from './gapiScript';
```

**Comment by LucasAndrad** [comment]
Hey @jwknz thanks for the report. 

Can you give more details about this error and your project?
Like, the framework you're using, when this error appears, anything.
